[build]
  publish = "out"
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Essential for Netlify Next.js plugin
[context.production]
  command = "pnpm build"

[context.deploy-preview]
  command = "pnpm build"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200